### ISSUE TITLE
frozen atom shall be an input atom

### ISSUE THREAD

**Issue by broesdecat** [potassco/clingcon#1]
Hi,

When running a clingcon specification with clingcon 3.2.1, I get the following error:
void Clasp::Asp::LogicProgram::updateFrozenAtoms()@1032: contract violated: frozen atom shall be an input atom

I guess such an error is automatically a bug, or is it possible my input is invalid?
Otherwise I will try to reduce my problem to a smaller, anonimized file :)

Best,
Broes

**Comment by MaxOstrowski** [comment]
Could you try the current master with your problem?
This bug should already be fixed, but without your problem at hand I can not check.
Release will take some more time, sorry for the delay.

**Comment by broesdecat** [comment]
Hi Max,

That's ok for me, I will try the development version. However, the build procedure in INSTALL.md does not work, can you indicate how I should build from source?
What I did:
- clone clingcon
- update all git submodules (recursively)
- `scons --build-dir=release` in the clingcon folder. First file it tries to compile is `app/clingcon/src/main.cc`.
-> Error `app/clingcon/src/clingcon_app.hh:29:23: fatal error: clasp_app.h: No such file or directory`

One issue seems to be that the folder is `clingo/clasp` and not `clingo/libclasp`, but changing that in the scons file resulted in additional files not being found, and after some more changes, I gave up.

Best,
Broes

**Comment by MaxOstrowski** [comment]
Hi,
I currently try to change the build system in the master.
This is why you have problems compiling it.
I'm in the process of switching from scons to CMake. But unfortunately,
I had to stop in the middle of the process to get some papers done.
So feel free to give CMake a try, otherwise you have to wait 2-3 weeks
for me to finish
the build steps.

Best,
Max

Am 08.05.2017 um 15:19 schrieb Broes De Cat:

**Comment by broesdecat** [comment]
Hi Max,

I got it compiled with cmake and the issues I reported have indeed been
resolved.

Thx!
Broes

**Comment by MaxOstrowski** [comment]
This is great news.
Let me know if you need any additional help.

Best,
Max
