### ISSUE TITLE
Undefined symbols for architecture x86_64: "std::uncaught_exceptions()"

### ISSUE THREAD

**Issue by barracuda156** [potassco/clingcon#101]
We get this error on 10.7–10.11 now:
```
Undefined symbols for architecture x86_64:
  "std::uncaught_exceptions()", referenced from:
      Catch::ScopedMessage::~ScopedMessage() in main.cc.o
      Catch::uncaught_exceptions() in main.cc.o
      Catch::Capturer::~Capturer() in main.cc.o
      Catch::Section::~Section() in main.cc.o
ld: symbol(s) not found for architecture x86_64
```
Log: https://build.macports.org/builders/ports-10.11_x86_64-builder/builds/207256/steps/install-port/logs/stdio

Probably will be fixed once `catch2` updated. Similar error with another port: https://github.com/AnyarInc/Ascent/issues/26

**Comment by rkaminsk** [comment]
Since you managed to get clingo running which also uses catch, maybe you could blacklist compilers again?

**Comment by barracuda156** [comment]
> Since you managed to get clingo running which also uses catch, maybe you could blacklist compilers again?

I did in fact, but this error is caused by `catch2`, it seems, not by a compiler. See the ticket I referred.
