### ISSUE TITLE
Default Options do not compute optimal model

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingcon#33]
If a theory minimization statement is present, still only one model is computed.
Workaround: `--models=0`

**Comment by rkaminsk** [comment]
Clasp automatically sets this option based on the problem. Of course it does not know about clingcon's minimize statement. It would be nice to have something like this in clingcon too. I don't find it terribly important though.

**Comment by MaxOstrowski** [comment]
When testing the minizinc benchmarks these are mixed classes of optimization and non-optimization problems. So it will be important for me and I will look into it once I find the time.

**Comment by MaxOstrowski** [comment]
Btw: Is there a way using the API to tell if an option was changed via command line?
In case a user enters `--models=1` I do not want to change it to `0` if it is a clingcon optimization problem.

**Comment by rkaminsk** [comment]
> Btw: Is there a way using the API to tell if an option was changed via command line?
> In case a user enters `--models=1` I do not want to change it to `0` if it is a clingcon optimization problem.

I don't know. For your benchmarks, you could simply divide your instances into two sets. This makes sense anyway because sat and optimization problems behave very differently.

**Comment by MaxOstrowski** [comment]
Sure, thanks.

**Comment by MaxOstrowski** [comment]
Minizinc announced their yearly competition and we are thinking about participating.
To be compatible with the requirements the solver needs to compute optimal solutions if the problem contains an optimize statement (just like clingo).
I tried to implement this in `clingcon_prepare`. Unfortunately, `has_minimize` is still false until we added the minimize statement during `init()`.
I do not know how to get the Control::configuration() object during the solve process (using PropagateInit, etc...). Is this something that I can do ?

Another option could be in the `clingcon_rewrite_statement` function (haven't managed to fully understand these nested lambdas). Here again would be the problem, wheren can I get access to Clingo::Control to change ["solver"]["models"] configuration.

Any more ideas ?

**Comment by rkaminsk** [comment]
What about a script with a grep to figure out whether there is an optimization problem? Otherwise, you can loop over the theory data after grounding in the `main.cc` file.

**Comment by MaxOstrowski** [comment]
It'll do for the competition I guess.
I was afraid of performance, as I have to grep the flatzinc (grounded) file. But it'll work for now. Thx

**Comment by rkaminsk** [comment]
A grep should be really fast. I don't think it will have a big effect. Otherwise, there is my second remark...

**Comment by rkaminsk** [comment]
Since you are mentioning this issue again, automatically setting the models to 0 is possible. By default we have
```python
>>> ctl.configuration.solve.models
-1
```
which stands for auto as described in clasp's help output. This means you can set it to 0 in the main function if there is a minimize constraint in the program and the current value is `-1`.

**Comment by rkaminsk** [comment]
And I still don't think this is a bug. It's just like this. :smile:

**Comment by MaxOstrowski** [comment]
Awesome, thanks.

**Comment by MaxOstrowski** [comment]
Fixed in wip branch. conda releases pending.
