### ISSUE TITLE
No tuples in distinct

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingcon#34]
```
in(0,a).
in(1,b).
in(2,a).
&distinct {V,I : in(I, V)}.
```

**Comment by rkaminsk** [comment]
Yes, no tuples. Just write
```
&distinct {V : in(I, V)}.
```
This should also be consistent with clingcon's other theory atoms. I decided to do it like this to avoid taking sets of terms. With multi-sets, tuples make no sense.

**Comment by MaxOstrowski** [comment]
In the case of distinct, it completely makes no sense to have the same parameter twice.
So distinct is clearly a set.

**Comment by rkaminsk** [comment]
> In the case of distinct, it completely makes no sense to have the same parameter twice.
> So distinct is clearly a set.

With one element maybe but not with multiple ones:
```
&distinct {A : a(A); B : b(A)}.
```
In any case we have multi-set semantics then.

**Comment by MaxOstrowski** [comment]
What I meant is that any distinct is false where a variable occurs twice! So why would you want to write such a thing...

**Comment by rkaminsk** [comment]
> What I meant is that any distinct is false where a variable occurs twice! So why would you want to write such a thing...

This would only make sense with non-domain conditions...
