### ISSUE TITLE
Atoms in constraints

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingcon#36]
I have just seen in chuffed that normal atoms can be used in linear constraints.
{a;b;c}.
`&sum{3*a;2*b;4*c} = x.`
This mixture of boolean and non-boolean variables allows for easy implementation of the following global constraints:
```
atleast
atmost
exactly
count
distribute
global_cardinality_low_up
nvalue
```
Currently this would break encodings (as we do not know when a "variable" is of type int or bool.
But something like this would be cool.
Any thoughs ? @rkaminsk

**Comment by rkaminsk** [comment]
I think that this is more trouble than it is worth. Boolean and integer variables should be separate. In any case this can be encoded. The encoding below should already do the right thing (including using `a` directly as an order literal).

    &dom{0..1} = a.
    &sum {a} >= 1 :- a.
    &sum {a} <= 0 :- not a.

**Comment by MaxOstrowski** [comment]
Awesome, thx!
