### ISSUE TITLE
Is it possibe to use PB constraints for linear constraints over 0/1 Variables

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingcon#37]
Is it possible to introduce aggregates/PB constraints to directly translate linear constraints over 0/1 variables ? This happens quite often when solving CP minizinc encodings.

**Comment by rkaminsk** [comment]
The translate to weight constraint implementation should already do just the right thing. Since the translation is completely useless in general case, you can change the estimate function into a test that checks if all variables are 0/1.

**Comment by MaxOstrowski** [comment]
Plan: Change the `--translate-pb=n` option to a flag that simply translates all Boolean linear constraints to PB constraints. This should have precedence over the clause translation. Evaluate this using minizinc challenge benchmarks 2019/2020.
