### ISSUE TITLE
clingcon with MIT license?

### ISSUE THREAD

**Issue by tortinator** [potassco/clingcon#4]
I would suggest to move clingcon to MIT license
Is this just an omission?

**Comment by MaxOstrowski** [comment]
probably just an omission.
Old clingcon had MIT license.

Am 28.10.2017 um 15:16 schrieb Torsten Schaub:

**Comment by rkaminsk** [comment]
@MaxOstrowski: If you change the license, it is not enough to just change the license file. You also have to change all the preambles in the source files.

**Comment by MaxOstrowski** [comment]
I did so in the max/wip branch and will merge once I got the rest running. Is this ok ?

**Comment by rkaminsk** [comment]
I was going through my notifications and stumbled over it. Just wanted to tell you. Merge whenever you like.

**Comment by MaxOstrowski** [comment]
Thanks.
