### ISSUE TITLE
Bounded command line options

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingcon#45]
Some command line options need to be bounded, like
- translate-opt as domains of 2^30 are possible this should be bounded by a parameter
- translate-clauses bounds the number of clauses per constraint, but the total number of introduced clauses should also be bounded in case of 100k+ constraints

**Comment by rkaminsk** [comment]
>     * translate-opt as domains of 2^30 are possible this should be bounded by a parameter
With this option another optimization algorithm is used that has many more features. Even the output looks different. Hence, I would not add a parameter.

>     * translate-clauses bounds the number of clauses per constraint, but the total number of introduced clauses should also be bounded in case of 100k+ constraints
This sounds reasonable.

**Comment by MaxOstrowski** [comment]
Branch feature/restrictclauses adds option --translate-clauses-total to restrict the total number of added clauses.
Currently, test fs/fso fails non-deterministically. Why is there non-deterministic behaviour at all ?!?!

**Comment by rkaminsk** [comment]
> Branch feature/restrictclauses adds option --translate-clauses-total to restrict the total number of added clauses.
> Currently, test fs/fso fails non-deterministically. Why is there non-deterministic behaviour at all ?!?!
> EDIT: maybe order of constraints that are translated (or not) ? Why does it prune solutions.

The tests use multi-shot solving. If there is a failure then there is most likely a bug, which we must not ignore.
