### ISSUE TITLE
ClingconTheory not considering minimize

### ISSUE THREAD

**Issue by susuhahnml** [potassco/clingcon#59]
The minimize option for clingcon `&minimize` is not working as expected when registering clingcon theory in clingo's API.  The result includes all models without performing any optimization, insted of returning just the minimal as in the direct call to a clingcon installation. 

Example:

```
from clingo import Control
from clingo.ast import parse_string, ProgramBuilder
from clingcon import ClingconTheory

prg = '&dom{1..4} = x. &minimize {x}.'

thy = ClingconTheory()
ctl = Control(['0'])
thy.register(ctl)
with ProgramBuilder(ctl) as bld:
    parse_string(prg, lambda ast: thy.rewrite_ast(ast, bld.add))

ctl.ground([('base', [])])
thy.prepare(ctl)
with ctl.solve(yield_=True) as hnd:
    for mdl in hnd:
        print([f'{key}={val}' for key, val in thy.assignment(mdl.thread_id)])
```

Expected: One model with `[x=1]`
Obtained:  `['x=1'] ['x=2'] ['x=3'] ['x=4']`

**Comment by rkaminsk** [comment]
It has to be `ctl.solve(yield_=True, on_model=thy.on_model)`. Then, the last model printed should be the optimal one.
