### ISSUE TITLE
build fail on cygwin

### ISSUE THREAD

**Issue by rekino** [potassco/clingcon#6]
Hi, I am following the install instructions in the repo but i get the following error when building:

`[ 44%] Built target libreify
[ 45%] [RE2C][groundtermlexer] Building lexer with re2c 0.16.0
re2c: error: cannot open source file: /cygdrive/d/potassco/clingcon/clingo/libgringo//src/input/groundtermlexer.xh
make[2]: *** [clingo/libgringo/CMakeFiles/libgringo.dir/build.make:62: clingo/libgringo/src/input/groundtermlexer.hh] Error 1
make[1]: *** [CMakeFiles/Makefile2:317: clingo/libgringo/CMakeFiles/libgringo.dir/all] Error 2
make: *** [Makefile:139: all] Error 2`

i guess the error is caused by double slashes in "...ringo//src/in..." (line 3), otherwise the file do exist in that address.

i downloaded the re2c.exe from "http://cs.uni-potsdam.de/~kaminski/re2c.exe"

**Comment by rekino** [comment]
replaced "/cygdrive/d/potassco/clingcon/clingo/libgringo//src/input/groundtermlexer.xh" 
 in "build.make" with "D:\\potassco\\clingcon\\clingo\\libgringo\\src\\input\\groundtermlexer.xh" and it worked

**Comment by rekino** [comment]
it failed again in compiling "groundparser.cc" because it couldn't find "/input/groundtermlexer.hh". replaced
`#include "/input/groundtermlexer.hh"`
with
`#include "groundtermlexer.hh"`
and it got passed the error

**Comment by rkaminsk** [comment]
The re2c binary you used is not a cygwin binary, so it cannot deal with Unix paths. I would suggest, you simply compile re2c in the cygwin environment. Just get the source, configure, and make and you are ready to go.

**Comment by rekino** [comment]
It is so difficult to compile re2c. Even though I managed to compile and run clingcon using the hacks I mentioned earlier, the executable is not portable; it doesn't work on other Windows systems even if I install Cygwin, it nags about cygwin1.dll and how it is not made for this version of Windows. So I regretfully had to revert to msvc++.

**Comment by rkaminsk** [comment]
For me compiling re2c always worked without problems. Here is the script I use to build it on appveyor. You might want to set another prefix though:

```bash
wget https://github.com/skvadrik/re2c/releases/download/0.16/re2c-0.16.tar.gz
tar xf re2c-0.16.tar.gz
cd re2c-0.16
./configure --prefix=/usr
make -j3
make install
```

**Comment by rkaminsk** [comment]
To make the executable portable you have to link at least the cygwin library statically. Adding -static to the linker options should be enough. But also make sure that no shared libraries are build.

**Comment by rekino** [comment]
hm, I was trying to build re2c from source, in which './autogen.sh' had to be executed first, not a pretty sight! It works fine using distros as you mentioned.
Unfortunately, I cannot find anything on adding -static to linker options, how is it done?

**Comment by rekino** [comment]
found it. it is  -DCMAKE_LINKER_FLAGS or something, it could be found by running:
`cmake -B <BUILD_DIR> -LAH`
