### ISSUE TITLE
minimize ignored without --translate-opt=max

### ISSUE THREAD

**Issue by mbalduccini** [potassco/clingcon#64]
Hi,
I was testing the new release 5.0.0 and noticed that minimization doesn't occur for some programs unless I use `--translate-opt=max`.
For example, the program:
```
&dom { -5..0 } = a.
&sum { a } >= -3.
&minimize { a }.
&show { a }.
```
produces `a=0` while the correct result is `a=-3`. With `--translate-opt=max`, the correct result is produced. I verified that the same behavior is present in master (clingcon reports version 5.0.1). I am not sure if this is the intended behavior.

**Comment by MaxOstrowski** [comment]
If the minimize statement is not translated you currently need to set the number of models you want to enumerate to 0(all). So, rule of thumb for now is to call 'clingo 0' if your has an optimization statement.

Sorry for the hazzle, the API would need to be extended to properly handle this case.

**Comment by mbalduccini** [comment]
Note, thanks!!

**Comment by MaxOstrowski** [comment]
Fixed in wip branch. conda releases pending.
