### ISSUE TITLE
Support for --mode option in clingcon 5?

### ISSUE THREAD

**Issue by mbalduccini** [potassco/clingcon#67]
Clingcon 3 had the very convenient feature of allowing one to ground and solve a program separately by means of `--mode=gringo` and `--mode=clasp`. Is it possible to achieve a similar result in clingcon 5? In my tests I was not able to get it to behave as I would have expected. For instance, given the program test01.cl5:
```
&dom{ 0..5 }=a.
&sum{ a } > 5.
```
the command `clingcon test01.cl5` yields the expected result that the program is unsatisfiable, while the command `clingcon test01.cl5 --mode=gringo | clingcon -   --mode=clasp` does not, rather producing:
```
clingcon version 5.0.1
Reading from -
Solving...
Answer: 1

SATISFIABLE

Models       : 1+
Calls        : 1
Time         : 0.002s (Solving: 0.00s 1st Model: 0.00s Unsat: 0.00s)
CPU Time     : 0.001s
```

Any help is greatly appreciated!

**Comment by rkaminsk** [comment]
There is no support for this atm. Implementing this would require a bit of work on clingo.

**Comment by mbalduccini** [comment]
Ah, that's unfortunate! Can you suggest any other way of processing pre-grounded (or externally grounded) programs? Perhaps there is a way through the API if I write a custom Python main?

**Comment by rkaminsk** [comment]
I do not see a way to do this with the current API without extending either clingo or clingcon. Neither does the backend support adding theory atoms nor is there a way to load files in aspif format.

**Comment by mbalduccini** [comment]
Got it, thanks!
