### ISSUE TITLE
clingcon 3.3.0 and option --project

### ISSUE THREAD

**Issue by ngominhduc** [potassco/clingcon#7]
Dear sir,
I'm surprised to get only one answer set from the following program submitted to clingcon 3.3.0 with the option "--project".

#include <csp>.

&dom{1..3} = delay1.
&dom{1..3} = delay2.

&sum{delay1; - delay2} = 0.

&show{delay1}.
&show{delay2}.
............
clingcon version 3.3.0
Reading from test.lp
Solving...
Answer: 1
delay2=3 delay1=3
SATISFIABLE

Models       : 1
Calls        : 1
Time         : 0.002s (Solving: 0.00s 1st Model: 0.00s Unsat: 0.00s)
CPU Time     : 0.002s

with no option "--project", we get 3 answer sets :

......
clingcon version 3.3.0
Reading from test.lp
Solving...
Answer: 1
delay2=3 delay1=3
Answer: 2
delay2=2 delay1=2
Answer: 3
delay2=1 delay1=1
SATISFIABLE

Models       : 3
Calls        : 1
Time         : 0.002s (Solving: 0.00s 1st Model: 0.00s Unsat: 0.00s)
CPU Time     : 0.002s

Could you explain to me why ?
Thank you,
Sincerely yours.
NGO Minh Duc.
from lab TIMC-IMAG, in Grenoble, France.

**Comment by MaxOstrowski** [comment]
The projection option is not supposed to work on theory variables, but on atoms.
So you basically project on the empty set of atoms. Therefore you will only have one answer set (the empty one) with a (random) assignment of the constraint variables.
These constraint variables are not to be confused with atoms.

The project option allows to to project on some ASP atoms while you still asure the consistency of the non-Boolean constraints. It does not work the other way around, as I currently do not see a possibility to implement it.

I will reopen this once I have the time and an idea how to implement such a feature. Please feel free to add your ideas.
