### ISSUE TITLE
Unnecessary code

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingcon#74]
https://github.com/potassco/clingcon/blob/289b80ca4b2f936625bb6e6d35d7c6a4da6e3fd7/libclingcon/src/solver.cc#L664-L675

Isn't this exactly the same code executed twice ? Can I remove the second clause ?

**Comment by rkaminsk** [comment]
Yes, it is the same thing. Also the comment is just the contraposition. You can remove one of them (preferably the second).
