### ISSUE TITLE
error syntx

### ISSUE THREAD

**Issue by ngominhduc** [potassco/clingcon#8]
Dear sir,
I have some problem with the new syntax of clingcon v3.3.0. Before, i use that for programming

1 $<= $x $<= 3.
1 $<= $y $<= 3.

1{$x $= 1; $y $= 2}1.

Solving....................
Answer: 1
y=2 x=3
Answer: 2
x=2 y=2
Answer: 3
x=1 y=1
Answer: 4
x=1 y=3
SATISFIABLE

Models       : 4
Calls        : 1
Time         : 0.001s (Solving: 0.00s 1st Model: 0.00s Unsat: 0.00s)
CPU Time     : 0.001s

and with new version of clincon, there are a syntax error

#include <csp>.

&dom{1..3} = x.
&dom{1..3} = y.

1{&sum{x} = 1; &sum{y} = 2}1.

Reading from test3.lp
test3.lp:6:3-4: error: syntax error, unexpected &

*** ERROR: (clingcon): parsing failed
UNKNOWN

Models       : 0+
Calls        : 1
Time         : 0.021s (Solving: 0.00s 1st Model: 0.00s Unsat: 0.00s)
CPU Time     : 0.021s

Same problem with the following syntax:

1 $<= $x $<= 3.
1 $<= $y $<= 3.

p(x).
p(y).

$X $= 2 : p(X).

clingcon version 3.3.0
Reading from test5.lp
Solving...
Answer: 1
p(x) p(y) y=2 x=3
Answer: 2
p(x) p(y) x=2 y=2
Answer: 3
p(x) p(y) x=1 y=2
Answer: 4
p(x) p(y) x=2 y=3
Answer: 5
p(x) p(y) y=1 x=2
SATISFIABLE

Models       : 5
Calls        : 1
Time         : 0.001s (Solving: 0.00s 1st Model: 0.00s Unsat: 0.00s)
CPU Time     : 0.001s

and with new version of clincon,

#include <csp>.

&dom{1..3} = x.
&dom{1..3} = y.

p(x).
p(y).

&sum{X} = 2 : p(X).

clingcon version 3.3.0
Reading from test5.lp
test5.lp:9:13-14: error: syntax error, unexpected :, expecting . or :-

*** ERROR: (clingcon): parsing failed
UNKNOWN

Models       : 0+
Calls        : 1
Time         : 0.008s (Solving: 0.00s 1st Model: 0.00s Unsat: 0.00s)
CPU Time     : 0.008s

Could you explain to me why ?
Thank you,
Sincerely yours.
NGO Minh Duc.
from lab TIMC-IMAG, in Grenoble, France.

**Comment by MaxOstrowski** [comment]
Sorry that you had to wait, I was on Vacation.

> 1{&sum{x} = 1; &sum{y} = 2}1.
I'm sorry, but TheoryAtoms are not allowed in aggregates as they have aggregate like behavior.
You have to write a workaround with aux variables for this.

> &sum{X} = 2 : p(X).
If you want to accumulate the X's, the corrent syntax should be:
&sum{X : p(X)} = 2.

Sorry for the brief answer.
